api_platform:
    title: "WAVE Trophy API"
    version: 1.0.0
    path_segment_name_generator: api_platform.path_segment_name_generator.dash

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header

    enable_fos_user: true