easy_admin:
  site_name: 'WAVE Trophy App'
  design:
    form_theme:
      #      - '@EasyAdmin/form/bootstrap_4.html.twig'
      # the following Twig template can be located anywhere in the application.
      # it can also be added to the twig.form_themes option to use it in the
      # entire application, not only the backend
      - 'admin/form.html.twig'
    brand_color: '#8BA654'

    menu:
      - label: 'User'
        children:
          - { label: 'Users', entity: 'User' }
          - { label: ' - Emails', entity: 'UserEmail' }
          - { label: ' - Phonenumbers', entity: 'UserPhonenumber' }
      - label: 'Wave'
        children:
          - { label: 'Wave', entity: 'Wave' }
          # - { label: 'Location', entity: 'Location' }
          - { label: 'Group', entity: 'Group' }
          - { label: 'Team', entity: 'Team' }
          - { label: 'Events', entity: 'Event' }
          - { label: 'Hotel', entity: 'Hotel' }
        # - { label: 'Lodging', entity: 'Lodging' }
      - { label: 'Docs', url: '/docs/index.html' }


  entities:

    Wave:
      class: App\Entity\Wave
      list:
        fields:
          - 'name'
          - 'country'
          - 'start'
          - 'end'
      form:
        fields:
          - 'name'
          - 'country'
          - 'start'
          - 'end'

    # Location:
    #   class: App\Entity\Location
    #   list:
    #     dql_filter: 'entity.deletedAt is NULL'
    #     fields:
    #       - 'name'
    #       - 'wave'
    #   form:
    #     fields:
    #       - { property: 'thumbnailImage', type: 'vich_image' }
    #       - 'name'
    #       - 'wave'
    #       - { property: 'location' , type_options: { block_name: 'selection' } }
    #
    #    new:
    #      fields:
    #        - { property: 'thumbnailImage', type: 'vich_image', type_options: { required: false }}
    #    edit:
    #      fields:
    #        - { property: 'thumbnailImage', type: 'vich_image', type_options: { required: false }}

    Event:
      class: App\Entity\Event
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'name'
          - 'description'
          - 'start'
          - 'end'
          - 'location'
      form:
        fields:
          - 'name'
          - 'description'
          - 'start'
          - 'end'
          - 'location'

    Group:
      class: App\Entity\Group
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'name'
          - 'wave'
      form:
        fields:
          - 'name'
          - 'wave'

    Hotel:
      class: App\Entity\Hotel
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'name'
          - 'checkIn'
          - 'checkOut'
        # Form is defined in AdminController

    # Hide this due to much information for louis :)
    # Lodging:
    #   class: App\Entity\Lodging
    #   list:
    #     fields:
    #       - 'hotel'
    #       - 'comment'
    #       - 'users'
    #   form:
    #     fields:
    #       - 'comment'
    #       - 'hotel'
    #       - 'users'

    Team:
      class: App\Entity\Team
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'name'
          - 'startNumber'
          - 'group'
          - 'users'
      form:
        fields:
          - 'name'
          - 'startNumber'
          - 'group'
          - 'users'

    eventparticipation:
      class: App\Entity\EventParticipation
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'arrival'
          - 'departure'
          - 'location'
      form:
        fields:
          - 'arrival'
          - 'departure'
          - 'location'
          - { property: 'teams', type: 'entity', type_options: { class: 'App\Entity\Team', multiple: true } }

    User:
      controller: App\Controller\UserEditController
      class: App\Entity\User
      list:
        dql_filter: 'entity.deletedAt IS NULL'
        fields:
          - 'email'
          - 'firstName'
          - 'lastName'
          - 'team'
      form:
        fields:
          - 'email'
          - 'firstName'
          - 'lastName'
          - 'team'
      edit:
        fields:
          - '-email'
          - 'emails'
          - { property: 'plainPassword', type: 'password', type_options: { required: false } }

    UserEmail:
      class: App\Entity\UserEmail
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'email'
          - 'isPublic'
          - 'user'
        actions: ['-delete']
      form:
        fields:
          - 'email'
          - 'isPublic'
          - 'user'

    UserPhonenumber:
      class: App\Entity\UserPhonenumber

      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'countryCode'
          - 'phonenumber'
          - 'isPublic'
          - 'user'
      form:
        fields:
          - 'countryCode'
          - 'phonenumber'
          - 'isPublic'
          - 'user'
