easy_admin:
  site_name: 'WAVE Trophy App'
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      # the following Twig template can be located anywhere in the application.
      # it can also be added to the twig.form_themes option to use it in the
      # entire application, not only the backend
      - 'admin/form.html.twig'
    brand_color: '#8BA654'

    menu:
      - label: 'User'
        children:
          - { label: 'Users', entity: 'User' }
          - { label: ' - Emails', entity: 'UserEmail' }
          - { label: ' - Phonenumbers', entity: 'UserPhonenumber' }
      - label: 'Wave'
        children:
          - { label: 'Wave', entity: 'Wave' }
          - { label: 'Location', entity: 'Location' }
          - { label: ' - Event', entity: 'Event' }
          - { label: 'Group', entity: 'Group' }
          - { label: 'Team', entity: 'Team' }
          - { label: ' - Team Participation', entity: 'TeamParticipation' }
          - { label: 'Hotel', entity: 'Hotel' }
          - { label: 'Lodging', entity: 'Lodging' }

  entities:

    Wave:
      class: App\Entity\Wave
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'name'
          - 'country'
          - 'start'
          - 'end'
      form:
        fields:
          - 'name'
          - 'country'
          - 'start'
          - 'end'

    Location:
      class: App\Entity\Location
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'name'
          - 'wave'
      form:
        fields:
          - 'name'
          - 'wave'
          - { property: location, type_options: { block_name: 'selection' } }

    Event:
      class: App\Entity\Event
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'name'
          - 'description'
          - 'start'
          - 'end'
          - 'location'
      form:
        fields:
          - 'name'
          - 'description'
          - 'start'
          - 'end'
          - 'location'

    Group:
      class: App\Entity\Group
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'name'
          - 'wave'
      form:
        fields:
          - 'name'
          - 'wave'

    Hotel:
      class: App\Entity\Hotel
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'name'
          - 'breakfastIncluded'
          - 'lastCheckIn'
          - 'comment'
          - 'location'
      form:
        fields:
          - 'name'
          - 'breakfastIncluded'
          - 'lastCheckIn'
          - 'comment'
          - 'location'

    Lodging:
      class: App\Entity\Lodging
      list:
        fields:
          - 'id'
          - 'hotel'
          - 'comment'
          - 'users'
      form:
        fields:
          - 'comment'
          - 'hotel'
          - 'users'

    Team:
      class: App\Entity\Team
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'name'
          - 'startNumber'
          - 'group'
          - 'users'
      form:
        fields:
          - 'name'
          - 'startNumber'
          - 'group'
          - 'users'

    TeamParticipation:
      class: App\Entity\TeamParticipation
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'arrival'
          - 'departure'
          - 'location'
      form:
        fields:
          - 'arrival'
          - 'departure'
          - 'location'
          - { property: 'teams', type: 'entity', type_options: { class: 'App\Entity\Team', multiple: true } }

    User:
      controller: App\Controller\UserEditController
      class: App\Entity\User
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'email'
          - 'firstName'
          - 'lastName'
          - 'team'
      form:
        fields:
          - 'email'
          - 'firstName'
          - 'lastName'
          - 'team'
          - 'profilePicture'
      edit:
        fields:
          - '-email'
          - 'emails'

    UserEmail:
      class: App\Entity\UserEmail
      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'email'
          - 'isPublic'
          - 'user'
      form:
        fields:
          - 'email'
          - 'isPublic'
          - 'user'

    UserPhonenumber:
      class: App\Entity\UserPhonenumber

      list:
        dql_filter: 'entity.deletedAt is NULL'
        fields:
          - 'id'
          - 'countryCode'
          - 'phonenumber'
          - 'isPublic'
          - 'user'
      form:
        fields:
          - 'countryCode'
          - 'phonenumber'
          - 'isPublic'
          - 'user'
