lexik_jwt_authentication:
    private_key_path: '%env(file:resolve:JWT_SECRET_KEY)%'
    public_key_path:  '%env(file:resolve:JWT_PUBLIC_KEY)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
    token_ttl:        3600
