vich_uploader:
  db_driver: orm

  mappings:
    media:
      uri_prefix: /media
      upload_destination: '%upload_directory%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      directory_namer:
        service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
        options: {date_time_format: 'Y/m/d'}