vich_uploader:
  db_driver: orm

  mappings:
    media:
      uri_prefix: /media
      upload_destination: '%upload_directory%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      directory_namer:
        service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
        options: {date_time_format: 'Y/m/d'}

    location_thumbnail:
      uri_prefix: /media/thumbnails/locations
      upload_destination: '%upload_directory%/thumbnails/locations'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    hotel_thumbnail:
      uri_prefix: /media/thumbnails/hotels
      upload_destination: '%upload_directory%/thumbnails/hotels'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    event_thumbnail:
      uri_prefix: /media/thumbnails/events
      upload_destination: '%upload_directory%/thumbnails/events'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
