#index:
#    path: /
#    controller: App\Controller\DefaultController::index
easy_admin_bundle:
  resource: 'App\Controller\AdminController'
  type:     annotation
  prefix:   /admin
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
