#index:
#    path: /
#    controller: App\Controller\DefaultController::index
easy_admin_bundle:
  resource: "@EasyAdminBundle/Controller/"
  type:     annotation
  prefix:   /admin
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
  path: /auth/login